name: ftp deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: dss.hosting.nyu.edu
          username: ${{secrets.FTP_USERNAME}}@$dss.hosting.nyu.edu
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./build/
          state-name: ./.ftp-deploy-sync-state.json
          server-dir: 'viewpoint/' # optional subdir, must end in /
